### PR TITLE
First steps

### PR DESCRIPTION
**Pull request by pwilms**
@hjdhjd  I've created a first basic implementation of unifi-access

**current features:**
- Exposing Door as Lock Mechanism
- Exposing additional Contact Sensor 
- Listing to websockt for updating the door position station
- homebrige ui integration for easy setup and fetching door ids
- updating readme
- cleanup and some refactoring

**next steps:**
- multiple doors
- testing (jest)
- some handling of edgecases
- github pipeline

devroom

settings

### CODE REVIEW

**Comment by hjdhjd** [comment]
Thanks for the contribution - will review in the coming days. I've also been working on my own code-base now that I've gotten homebridge-ratgdo out of the way. The challenge is, I want to ensure consistency across the other plugins I've written and maintain and there are a few challenges already I see...if I don't get to the finish line in short order I'll rebase to a version of what you've submitted. Stay tuned! Thanks again!

**Comment by pwilms** [comment]
@hjdhjd i'm still refactoring a little bit. If you need a permanent contributor / supporter on that gimme a ping.

**Comment by pwilms** [comment]
@hjdhjd  github actions and i've pushed first tests with vitest: https://github.com/pwilms/homebridge-unifi-access/actions/runs/8117906859/job/22191075781 

maybe thats something for you and your other plugins. 

I'll want to exclude the fetch api from that plugin to a separate package in next week.

**Comment by hjdhjd** [comment]
> @hjdhjd github actions and i've pushed first tests with vitest: https://github.com/pwilms/homebridge-unifi-access/actions/runs/8117906859/job/22191075781
> 
> maybe thats something for you and your other plugins.
> 
> I'll want to exclude the fetch api from that plugin to a separate package in next week.

There's already a CI/CD pipeline that's in use in my plugins. Thanks though.

**Comment by pwilms** [comment]
I know, I've just extend it with unit tests using vitest

**Comment by pwilms** [comment]
@hjdhjd i just saw that you created https://www.npmjs.com/package/unifi-access what i mentioned above for the upcoming week. You already know that there is a api documentation https://core-config-gfoz.uid.alpha.ui.com/configs/unifi-access/api_reference.pdf. I was confused in that package is username and password used but access is based on api tokens.

**Comment by hjdhjd** [comment]
As I mentioned in the documentation for the library and what I’ve been working on - the published API is constrained in what you can do, and largely limited to access policies, device enumeration, and open/close functionality. Its purpose is to provide clean integration points to larger enterprise access/security and certain SOHO solutions. That’s the API you’ve been building against and it’s token-based.

The true native API, such that it is, is capable of far more - motion detection, configuring of individual doorbell devices, etc. It’s accessed the same way that all UniFi APIs (Network, Protect, Connect, etc) are ultimately accessed, through a username and password.

Ultimately, my goal is to provide first-class support for both in the public API library and the native library in HBUA, though the focus will be on the richer feature set. My release is coincidental - I’ve been working my way through the native API for some time, just backlogged due to other projects. Part of what I’m working toward over the course of this work is to harmonize my libraries to create a consistent set of APIs across the UniFi ecosystem within the Node/JS/NPM ecosystem to simplify things for others.

More to come.

**Comment by Clausi821** [comment]
Hello, I've been following the project for a while and think it's great that you're continuing here.

I installed it today and can already control 2 hubs from the Home App, but the third one doesn't appear in the Home App. However, it's not a UA-Hub, but a UA-Hub-Door.

The UA-Hub-Door was purchased with the UA-G2-Pro in the kit.

I hope it's okay that I'm writing this here.

Best regards,
Tobias
Bildschirmfoto 2024-03-13 um 00 05 12

**Pull request closed without merging**
